[theme]
# Primary accent color for interactive elements.
primaryColor = "#6272a4"

# Background color for the main content area.
backgroundColor = "#282a36"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#44475a"

# Color used for almost all text.
textColor = "#fff"